### ISSUE TITLE
Bit-rot

### ISSUE THREAD

**Issue by anjohnson** [ChannelFinder/ChannelFinder.github.io#1]
This website is confusingly out of date and incomplete.
- Web Service link gives a 404 on this site.
- Other links point to the SourceForge site, and to Mercurial repo's on SF.
- The Issue tracking link points to a Jira instance on java.net.
- On the SourceForge Overview page, the links to the Design Paper and API Description are both dead.

The APS is looking for something like the Channel Finder for use with the Upgrade, but it's hard to point people to it at the moment. Without Carcassi is the ChannelFinder effectively now dead?

**Comment by shroffk** [comment]
Hello, 
We are in the process of moving channelfinder to the new website on github
https://github.com/ChannelFinder/ChannelFinderService/issues/16

We are in the process of rolling out a major release of channelfinder v3.0.

**Comment by anjohnson** [comment]
Hi Kunal,

Great. You can expect to hear from Dave Wallis here at APS about setting up an experimental CF system here.

Thanks,
- Andrew
